# Mod
mod_id = minecord
mod_name = Minecord
mod_description = Bring your Minecraft world into your Discord guild
## {x-release-please-start-version}
mod_version = 2.1.2+26.2
## {x-release-please-end}

# Fabric
minecraft_version = 26.2
loader_version = 0.19.3
yarn_mappings = 26.2+build.1
fabric_version = 0.155.2+26.2

# Dependencies
checkstyle_version = 12.3.0
jetbrains_annotations_version = 26.0.2
junit_jupiter_version = 6.0.1

# CurseForge
cf_project_id = 502254
cf_game_versions = Fabric, Java 25, 26.2
cf_relations_required = fabric-api
cf_relations_optional =
cf_relations_embedded = cloth-config
cf_relations_tools =
cf_relations_incompatible =

# Modrinth
mr_project_id = DoVQa3oa
mr_game_versions = 26.2
mr_relations_required = P7dR8mSH
mr_relations_optional =
mr_relations_incompatible =

# Publish
maven_group = me.axieum.mcmod.minecord
github_repo = axieum/minecord

# Other
org.gradle.jvmargs=-Xmx3G
